server:
  port: 8080

spring:  datasource:    url: jdbc:mysql://localhost:3306/akshay
    username: root
    password: root
  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate.dialect: MySQL8Dialect

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000